### ISSUE TITLE
Android 2.1.3 Webview Resource not found - Crash

### ISSUE THREAD

**Issue by erdincozden** [phrase/phrase-android#20] opened 2020-10-28 18:05 UTC
Hello,
App crashes when clicked on “copy” option selected text in android webview on many devices. There was no such problem before 2.1.3 release.
Best,

```
Fatal Exception: android.content.res.Resources$NotFoundException: Resource ID #0x2090005
       at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
       at android.content.res.Resources.getInteger(Resources.java:1115)
       at org.chromium.content.browser.selection.SelectionPopupControllerImpl.a(PG:207)
       at yY.onCreateActionMode(PG:15)
       at KW.onCreateActionMode(PG:6)
       at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onCreateActionMode(DecorView.java:2595)
       at com.android.internal.policy.DecorView.startActionMode(DecorView.java:913)
       at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:869)
       at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1008)
       at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1008)
       at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1008)
       at android.view.View.startActionMode(View.java:7324)
       at HL.a(PG:1)
       at org.chromium.content.browser.selection.SelectionPopupControllerImpl.h(PG:137)
       at LU.a(PG:31)
       at Lv.a(PG:14)
       at EI.run(:6)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by theSoenke** [comment] 2020-10-29 09:04
Hey @erdincozden, there appears to be a know issue in appcompat https://issuetracker.google.com/issues/141351441 We are currently looking for a solution to work with appcompat and webviews. This behavior with webviews is also reproducible for older versions of the SDK for me

**Comment by Runman44** [comment] 2020-12-14 09:18
@theSoenke - I'm using version 2.1.3 of the Phrase SDK, which in the release notes states its using appcompat 1.2.0 - but this issue is still present.

**Comment by theSoenke** [comment] 2020-12-16 10:19
@Runman44 The release 2.1.3 added support for the latest appcompat 1.2.0. This issue with webviews is unfortunately still present in the latest release and not directly related to the appcompat fix

**Comment by theSoenke** [comment] 2021-01-25 07:18
@erdincozden Version 3.0.0 of this SDK should resolve the webview related issues https://github.com/phrase/phrase-android/releases/tag/3.0.0

@Runman44 Could you please try using 3.0.0 as well? This release should fix all `appcompat` compatibility issues.

**Comment by theSoenke** [comment] 2021-01-25 07:18
I would now close this issue. Let me know in case you still should see anything unexpected

**Closed by theSoenke** 2021-01-25 07:18 UTC

**Comment by Papashkin** [comment] 2021-04-21 06:24
@theSoenke Hello!
I received one strange crash from the Firebase console:

```
Fatal Exception: android.content.res.Resources$NotFoundException: String resource ID #0xffffffff
       at android.content.res.Resources.getText(Resources.java:430)
       at android.content.res.HwResources.getText(HwResources.java:463)
       at com.phrase.android.sdk.inject.PhraseResources.getText(PhraseResources.java:13)
       at com.phrase.android.sdk.inject.PhraseResources.getString(PhraseResources.java)
       at android.content.Context.getString(Context.java:582)
       at io.coingaming.bitcasino.extensions.currency.CurrencyMapKt.getName(CurrencyMapKt.java:14)
```

I'm using Phrase 3.0.2, so the issue you mentioned above is not related to my case. It seems some other issue occurred here.
I checked all possible translations and tried to reproduce this error, but couldn't.

**Comment by theSoenke** [comment] 2021-04-27 13:22
Hey @Papashkin, we were unfortunately not able to reproduce this. Is there any chance that an invalid id is passed in into `getText`? There is also a possibility that this is related to an issue with webviews on certain Android devices/versions. Are you using webviews that might be related to this?

**Comment by Papashkin** [comment] 2021-04-27 13:25
Hei @theSoenke!
It seems that the problem has occurred on our side, so there is no error from the Phrase side.
Thanks for your time and have a nice day!

**Comment by theSoenke** [comment] 2021-04-27 13:29
Thanks a lot for the confirmation. Have a great day as well!

**Comment by timoEmberNjiuko** [comment] 2022-06-07 09:56
@Papashkin Hey Papashkin, i know its been a while, but do you know how you fixed the issue? We having a similar problem :) Thanks in advance!

**Comment by Papashkin** [comment] 2022-06-07 10:01
@timoEmberNjiuko hello!
I will try. Maybe the following way helps you.
We checked all available source IDs in both our app and a Phrase site. We found that one ID is existing for the Thai or Vietnamese language, but not for the default (English). Which was the source of the crash and error.
